# -*- coding: utf-8 -*-
"""Exercise 1: names

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqbFfrj3Gcx8dNT9WLpWWekqV4tlqrO2
"""

#Store the names of a few of your friends in a list called names. Print each person’s name by accessing each element in the list, one at a time.

friends = ["Kirby","James","Pare","Sebastian"]

print(friends[0])
print(friends[1])
print(friends[2])
print(friends[3])