# -*- coding: utf-8 -*-
"""Exercise 3: Your Own List

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqbFfrj3Gcx8dNT9WLpWWekqV4tlqrO2
"""

#Think of your favorite mode of transportation, such as a motorcycle or a car, and make a list that stores several examples. Use your list
#to print a series of statements about these items, such as “I would like to own a Honda motorcycle.”

modes_of_transportation= ["Motorcyle","Subaru WRX STi","Airplane","Boat"]

print("I'm not really fond riding a",modes_of_transportation[0])
print("A car that I would like to own is a",modes_of_transportation[1])
print("I always get excited when I get to ride an",modes_of_transportation[2])
print("One thing I don't neccesarily ride that often is a",modes_of_transportation[3])