# -*- coding: utf-8 -*-
"""Exercise 2: greetings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqbFfrj3Gcx8dNT9WLpWWekqV4tlqrO2
"""

#Start with the list you used in Exercise 1, but instead of just
#printing each person’s name, print a message to them. The text of each message should be the same, but each message should be
#personalized with the person’s name.

friends = ["Kirby","James","Pare","Sebastian"]

print("The Tallest is",friends[2])
print("The most aesthetic is",friends[0])
print("The anti-social is",friends[3])
print("The shortest is",friends[1])