# -*- coding: utf-8 -*-
"""Exercise 7: Seeing the World

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqbFfrj3Gcx8dNT9WLpWWekqV4tlqrO2
"""

#If you could invite anyone, living or deceased, to dinner, who would you invite? Make a list that includes at least three people you’d
#like to invite to dinner. Then use your list to print a message to each person, invitingthem to dinner.

dinner_guests = ["Angela","Kirby","Sebastian"]

#James couldn't come because of work

#Unfortunately we only have seats for 2 guests

print("Good day to you",dinner_guests[2],"unfortunately due to circumstances the dinner would have to rescheduled sorry")

#omitting one guest from the list

print(dinner_guests.pop(2),"Would be ommitted from the guest list")
print("The remaining guests would be",dinner_guests)

#printing remaining guests on list

print("Hey",dinner_guests[0],"If you're free tonight would you perhaps want to go on a dinner date with me? love you <3")
print("Good day to you",dinner_guests[1],"I would like to invite you to a dinner that I would be hosting")

#deleting all guests from list

del dinner_guests[:]
print(dinner_guests,"all guests have been omitted from the list")