# -*- coding: utf-8 -*-
"""Exercise 5:  change guest list

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cqbFfrj3Gcx8dNT9WLpWWekqV4tlqrO2
"""

#You just heard that one of your guests can’t make the dinner, so you need to send out a new set of invitations. You’ll have to think of someone else to invite.
#•Start with your program from Exercise 3-4. Add a print() call at the end of your program stating the name of the guest who can’t make it.
#•Modify your list, replacing the name of the guest who can’t make it with the name of the new person you are inviting.
#•Print a second set of invitation messages, one for each person who is still in your list.

   

dinner_guests = ["Angela","Kirby","James"]

#James couldn't come because of work

dinner_guests[2] = "Sebastian"

print("Hey",dinner_guests[0],"If you're free tonight would you perhaps want to go on a dinner date with me? love you <3")
print("Good day to you",dinner_guests[1],"I would like to invite you to a dinner that I would be hosting")
print("Good day to you",dinner_guests[2],"I would like to invite you to a dinner that I would be hosting")